Add Chinese Translation (2023.4.4)
xicri/genshin-langdata pull request #113
Opened 2023-04-04 01:12 UTC by SleepyAsh0191

Some things need pay attention to:
* I can't determine the word about Apep(new weekly boss)

2023-04-04 01:43 UTC, xicri requested changes
Thanks!
I added some comments.

2023-04-04 01:43 UTC, xicri commented on dataset/dictionary/characters.json5
> +    zhCN: "草龙(暂定)",   //TODO 中文版译名暂缺，“草龙”是俗称。
Let's comment out this Chinese translation until the accurate traslation is revealed.

2023-04-04 01:44 UTC, xicri commented on dataset/dictionary/characters.json5
> +    zhCN: "阿佩普",
> I can't determine the word about Apep(new weekly boss)

Can you ellaborate what you mean?

I checked the Simplified Chinese version of the v3.6 preview page, and 阿佩普 looks OK for the Chinese translation of Apep / アペプ.

I'm not sure if Apep / アペプ / 阿佩普 should be listed in the dictionary as a boss name, so I will determine after v3.6 release.
Guardian of Apep's Oasis / アペプのオアシス守護者 / 阿佩普的绿洲守望者 might be the correct boss name, and if so, I will change this translation.

2023-04-04 01:45 UTC, xicri commented
@Bill-Haku Can you review this PR as always?

2023-04-04 01:52 UTC, Bill-Haku commented on dataset/dictionary/characters.json5
> +    zhCN: "阿佩普",
Apep seems to be a name of the place, maybe we cannot get the name of the boss until the new version is released.

2023-04-04 01:53 UTC, Bill-Haku approved these changes

2023-04-04 02:11 UTC, xicri commented on dataset/dictionary/characters.json5
> +    zhCN: "草龙(暂定)",   //TODO 中文版译名暂缺，“草龙”是俗称。
Fixed in 810c233 and bb0a4d7.

2023-04-04 02:11 UTC, xicri approved these changes
@SleepyAsh0191 Thanks, looks good!

2023-04-04 02:12 UTC, merged

2023-04-12 08:10 UTC, xicri commented on dataset/dictionary/characters.json5
> +    // zhCN: "草龙(暂定)", TODO 中文版译名暂缺，“草龙”是俗称。
I found it.
Maybe 翠草之龙?

![zh-CN](https://user-images.githubusercontent.com/107226297/231394121-cce4e141-8b09-4178-ad61-a79680bfb464.png)
![en](https://user-images.githubusercontent.com/107226297/231394178-76f932fb-f246-4b28-8a0d-d502e19c7fc4.png)
![ja](https://user-images.githubusercontent.com/107226297/231394223-11fc3e01-61dd-4a20-904e-73a6bc303014.png)

2023-04-12 08:12 UTC, Bill-Haku commented on dataset/dictionary/characters.json5
> +    // zhCN: "草龙(暂定)", TODO 中文版译名暂缺，“草龙”是俗称。
That seems correct

2023-04-12 08:19 UTC, xicri commented on dataset/dictionary/characters.json5
> +    // zhCN: "草龙(暂定)", TODO 中文版译名暂缺，“草龙”是俗称。
@Bill-Haku Thanks, I'll apply by myself.
cc: @SleepyAsh0191

2023-04-12 10:57 UTC, xicri commented on dataset/dictionary/characters.json5
> +    // zhCN: "草龙(暂定)", TODO 中文版译名暂缺，“草龙”是俗称。
I just noticed these screenshots might be a spoiler... Apologies if you saw something you don't want to see yet.

2023-04-12 11:50 UTC, Bill-Haku commented on dataset/dictionary/characters.json5
> +    // zhCN: "草龙(暂定)", TODO 中文版译名暂缺，“草龙”是俗称。
It's okay. I don't mind it.