Add/Modify new keywords for Ver.4.6
xicri/genshin-langdata pull request #194
Opened 2024-04-29 16:58 UTC by yasuking0304

## Add/Modified new keywords for Ver.4.6

I referred to here and picked up the missing basic keywords.

- added version 4.5-4.6 characters
- added version 4.6 drops-boss
- added version 4.4-4.6 drops
- added version 4.6 enemies
- added version 4.6 items
- added version 4.4-4.6 foods
- added version 4.6 locations
- added version 4.6 weapons

### issue #193

2024-05-02 16:15 UTC, xicri commented
Sorry for the delay to respond, please wait a little bit more... 🙏

I quickly checked your commits and this PR includes the commits you made in the last PR.
Since it is very hard to review that, can you rebase it by the main?

```sh
cd path/to/genshin-langdata
git switch main
git fetch upstream
git rebase upstream/main
```

2024-05-05 13:10 UTC, yasuking0304 commented
Sorry. I ran rebased. If it doesn't work, I'll re-clone it and recreate the PR.

2024-05-05 20:09 UTC, xicri commented
Thanks, but still some old commits are remaining.
Can I rebase on my end? You have to pull this branch again after my rebase.

2024-05-06 00:25 UTC, xicri commented
@yasuking0304 Fixed.

2024-05-06 00:41 UTC, xicri requested changes
@yasuking0304 Thanks!
Please review the comments I added :bow:

2024-05-06 00:41 UTC, xicri commented on dataset/dictionary/characters.json5
> +    tags: [ "mondstadt", "character-sub" ],
Can you add `"event"` tag and move under events.json5?
I add the event-only characters in event.json5.

2024-05-06 00:41 UTC, xicri commented on dataset/dictionary/characters.json5
> +    notes: "「アルレッキーノ」の本名",
IMO, Peruere should be considered a main character.
I also want to add `enemy-boss`.

```suggestion
    tags: [ "snezhnaya", "fontaine", "character-main", "enemy-boss" ],
    notes: "アルレッキーノの本名",
```

2024-05-06 00:41 UTC, xicri commented on dataset/dictionary/characters.json5
> +    tags: [ "snezhnaya", "fontaine", "character-main" ],
Can you also add `enemy-boss` here?

```suggestion
    tags: [ "snezhnaya", "fontaine", "character-main", "enemy-boss" ],
```

2024-05-06 00:41 UTC, xicri commented on dataset/dictionary/characters.json5
> +    tags: [ "snezhnaya", "fontaine", "character-main", "title" ],
Can you also add `enemy-boss` here?

```suggestion
    tags: [ "snezhnaya", "fontaine", "character-main", "enemy-boss", "title" ],
```

2024-05-06 20:20 UTC, xicri commented
Since my change requests are not so large, I will commit them by myself.

2024-05-06 20:30 UTC, closed without merging

2024-05-06 20:31 UTC, xicri commented
Sorry, something went wrong and the PR is accidentally closed. Fixing...

2024-05-06 20:45 UTC, xicri commented
@yasuking0304 I couldn't restore this PR and I opened #195 instead.

Sorry, I accidentally overwrote your main branch with the current main branch of this repository (HEAD: c283672).
However, the changes you've sent in this PR are NOT lost.