Version 4.7 sequel
xicri/genshin-langdata pull request #237
Opened 2024-07-07 09:22 UTC by yasuking0304

Since we have advanced the story of the second half of Ver 4.7, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log".

Book(Item)

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|The Little Witch and the Undying Fire|小さな魔女と消えない炎|小魔女与不熄灭的火||| |
|The Feline Firm| ニャンコ事務所 | 猫咪事务所 ||| |

Charactor of Mondstadt

| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
|入力済み|イノシシプリンセス|-|書籍、並びに幻想シアターの控え室にある額縁の絵のキャラクター|NPC| 書籍としては登録済み tags:[Character (NPC), Mondstadt] |
|Wolfy|子オオカミ|子狼|幻想シアターの控え室に登場するキャラクター|NPC| |

Charactor of Fontaine

| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
|Rawat|ラワット|拉瓦特|| NPC||
|Potton|ポトン|波顿|| NPC||
|Wolsey|ウォルジー|韦尔赛|| NPC | 登場自体はVer. 4.1メロピデ要塞実装時から。特別許可食堂の料理長|
|Bran|ブラン|布兰|| NPC| 登場自体はVer. 4.1メロピデ要塞実装時から。特別許可食堂のマシナリー|
|The Witch|魔女婆さん|巫婆|シグウィンを人間の姿に変える薬を作った医者の先生| NPC|tags:[how to call]|

Charactor of Liyue

| English | Japanese | Chinese Simplifed | Note(ja) | Type |memo|
|---|---|---|---|---|---|
|Hautemontague|オートモンターニュ|沃特蒙泰涅|| NPC|登場自体はVer.4.4から tags:[liyue, fontaine]|

Food

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Well-Balanced Meal|栄養たっぷりバランス食|膳食均衡餐|シグウィンのオリジナル料理|ちなみに3日続けて働いたときに提供される福祉食ではない|
|Super-Dee-Duper Delicious Meat Roll|ウマウマシャワルマサンド|烤肉香香香卷|セトスのオリジナル料理|
|Tagged and Bagged|狩りの収穫|猎获|クロリンデのオリジナル料理|
|Hearthfire's Trail|炉火の昔語り|炉火的往迹|召使のオリジナル料理|
|Yummy Yum Cha|飲茶しようぜ！|得闲饮茶|嘉明のオリジナル料理|
|Pick What You Like!|どれでもどーぞ！|选你喜欢的！|ナヴィアのオリジナル料理|
|Bulle Sauce Duck Breast|鴨胸肉のオレンジソースソテー|桔香鸭胸肉||フォンテーヌのレシピ|
|Fontinalia Mousse|千霊ムース|千灵慕斯||フォンテーヌのレシピ|
|Consomme|コンソメスープ|百味一缕||フォンテーヌのレシピ|
|Rainbow Macarons|カラフルマカロン|缤纷马卡龙||フォンテーヌのレシピ|
|Honey Char Siu|蜜汁チャーシュー|蜜汁叉烧||璃月のレシピ|

Weapon
| English | Japanese | Chinese Simplifed | Note(ja) | type | memo |
|---|---|---|---|---|---|
| Silvershower Heartstrings | 白雨心弦(読み方不明) | 白雨心弦 || Bow | |

Domain
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Imaginarium Theater|幻想シアター|幻想真境剧诗| モンド騎士団本部の図書館の奥にある高難易度ダンジョン | |

Event

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
| Spino Doubleblaster |スプラッシュ・デュエット | 飞迸湍流二重奏 | Ver.4.7限定イベント||
| Endless Forms Most Martial |千変万化の豪傑譚 | 纷变繁相豪武谭 | Ver.4.7限定イベント||
| Record of Reflective Writing |ペンと空想の旅 | 绎思振笔集 | Ver.4.7限定イベント||
| Sprinting Stratagems | 奇策！スピード勝負 | 热斗模式: 奇策竞驰 | Ver.4.7限定イベント||

2024-07-07 09:29 UTC, yasuking0304 commented
Since the description of the [dataset/dictionary/weapons.json5](https://github.com/xicri/genshin-langdata/pull/237/files#diff-4e64a896f9cb0551d72e89e491aa6ed4f8ea07e745ec7b66f154b7240a49031a) did not match the specifications, the order was partially changed

2024-07-07 10:31 UTC, xicri commented
Thanks!

Can you rebase this branch with `main` to eliminate unnecesary commits?

2024-07-07 15:00 UTC, yasuking0304 commented
I rebased it.

2024-07-08 00:51 UTC, xicri commented
Thanks.
An empty commit c928a01 seems remained in the branch, so I will remove it then merge this PR.

2024-07-08 12:47 UTC, xicri requested changes

2024-07-08 12:48 UTC, xicri approved these changes

2024-07-08 12:49 UTC, merged