Add new keywords for Version 5.2 prequel genshin-langdata
xicri/genshin-langdata pull request #339
Opened 2024-12-12 14:24 UTC by yasuking0304

Since we have advanced the story, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log", item, voice, movie, Official YouTube channel.

Character of Liyue(ver 5.3)
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | type | memo |
|---|---|---|---|---|---|:-:|---|
| Lan Yan | 藍硯(らんやん) | 蓝砚 | | | | Playable | add tags:[liyue]<br>Playableは v5.3実装予定

Location of Snezhnaya
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | memo |
|---|---|---|---|---|---|---|
| Nod-Krai | ナド・クライ | 挪德卡莱 | | | | add tags:[Snezhnaya]<br>商人の立本からもたらされた情報

Organization of Snezhnaya
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | memo |
|---|---|---|---|---|---|---|
| Voynich Guild | ヴォイニッチ商会 | 伏尼契商会 | | | | add tags:[Snezhnaya]<br>商人の立本からもたらされた情報

<hr>

Events
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) | memo|
|---|---|---|---|---|---|---|
| Claw Convoy | アニマルトゥギャザー | 伴爪同行 | Limited Time Event in v5.2 | v5.2 期間限定イベント | v5.2 中的限时活动 | add tag:[events]
| Iktomi Spiritseeking Scrolls | スピリットを求めしウォーベン | 暝视寻灵织卷 | Limited Time Event in v5.2 | v5.2 期間限定イベント | v5.2 中的限时活动 | add tag:[events]
| Search for Lost Spilits | 探せ！ロストスピリット | 迷途灵性的搜觅 | v5.2 Sub-events of the Limited Time Event "Iktomi Spiritseeking Scrolls" | v5.2 期間限定イベント「スピリットを求めしウォーベン」の子イベント | 限时活动「暝视寻灵织卷」v5.2 子活动 | add tag:[events]
| Evil Banisher | イビル・パニッシュ | 斥逐与驱散恶客 | v5.2 Sub-events of the Limited Time Event "Iktomi Spiritseeking Scrolls" | v5.2 期間限定イベント「スピリットを求めしウォーベン」の子イベント | 限时活动「暝视寻灵织卷」v5.2 子活动 | add tag:[events]
| Restoring Fragmented Records | 千切れた古記録の復元 | 破碎旧录之规复 | v5.2 Sub-events of the Limited Time Event "Iktomi Spiritseeking Scrolls" | v5.2 期間限定イベント「スピリットを求めしウォーベン」の子イベント | 限时活动「暝视寻灵织卷」v5.2 子活动 | add tag:[events]
| Leyla | ルラ | 勒拉 | | v5.2 期間限定イベント「スピリットを求めしウォーベン」に登場する人物 | | tags: [ "event", "character-sub" ]
| Kokuchuu | 谷中(たになか) | 谷中 | | v5.2 期間限定イベント「スピリットを求めしウォーベン」に登場するアビス教団の使者。「淵上」「山下」と称するものと同一人物 | | tags: [ "event", "character-sub" ]

魔神任務
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) | memo|
|---|---|---|---|---|---|---|
| All Fires Fuel the Flame | 万火、一に帰す(ばんかいちにきす) | 万火归一 | | 魔神任務第五章幕間

部族見聞
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) | memo|
|---|---|---|---|---|---|---|
| Of Fading Flowers and Falling Feathers | 塵に帰す花、堕ちる羽(ちりにきすはなおちるはね) | 花之归尘，羽之将坠
| Memories Flowing With Color | 流れゆく色の記憶(ながれゆくいろのきおく) | 流淌着色彩的回忆

世界任務
| English | Japanese | Chinese Simplifed | Note(en) | Note(ja) | Note(zh-cn) | memo|
|---|---|---|---|---|---|---|
| From One Case to Another | 事件は次々に | 从一案到另一案
| Beat the Clock: 24 Hours | タイムリミットは二十四時間 | 时限二十四小时
| Dancin' in the Moonlight | 月光に舞え | 月光中共舞
| Lost Traveler in the Ashen Realm | 流灰の国の迷える旅人 | 流灰之国的迷旅人
| Sauro-Vet's Dilemma | 竜医の悩み | 龙医生的困境
| A Saurian Lover's Ordinary Days | とある竜マニアの平凡な暮らし | 爱龙人的平凡生活

Character
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | type | memo |
|---|---|---|---|---|---|:-:|---|
| Mutota | ムトタ | 穆托塔 | Chief, Flower-Feather Clan | 「花翼の集」族長 | 「花羽会」首领 | NPC
| Yopia | ヨピア | 尤庇娅 | | 第五章幕間に登場する人物
| Hueliyo | ウエリヨ | 胡里约 | | 第五章幕間に登場する人物
| Matlan | マトラン | 马特兰 | | 第五章幕間に登場する人物
| Atoco | アトコ | 阿图科 | | 第五章幕間に登場する人物
| Cohitta | コチッタ | 柯奇妲 | | 第五章幕間に登場する人物
| Ocotlan | オコトラン | 奥科兰 | | 第五章幕間に登場する人物
| Izcalli | イスカリ | 伊卡力 | | 第五章幕間に登場する人物
| Cuallee | クアリー | 库阿勒 | | 第五章幕間に登場する人物
| Munay | ムナイ | 穆纳伊 | | 第五章幕間に登場する人物
| Abundi | アバンディ | 阿邦迪 | Obsidian Totem Pole manager of "Flower-Feather Clan" |「花翼の集」の黒曜石トーテムポール管理人 | 「花羽会」曜石图腾柱管理员
| Allpa | アルパ | 阿尔帕 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Coyllur | コリユール | 科优尔 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Zunan | ジュナン | 朱南 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Mukki | ムッキ | 穆基 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Huascar | ワスカール | 瓦斯卡尔 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Pixica| ピシカ | 皮希加 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Cusco | クスコ | 库斯可 | | チャスカの育ての父親 | | | | 库は庫
| Coya | コヤ | 柯娅 | | 部族見聞「塵に帰す花、堕ちる羽」に登場するチャスカの姉同然のクク竜
| Chime | チメ | 奇梅 | | 部族見聞「塵に帰す花、堕ちる羽」に登場するコヤの子供の仔クク竜
| himpu | チンプ | 栖木普 | | 部族見聞「塵に帰す花、堕ちる羽」に登場するチャスカの育ての母同然のクク竜
| Inkanak | インカナック | 因卡纳克 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Tepal | テパル | 特帕尔 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Puma | プマー | 普玛 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Biram | ビラム | 庇兰 | Chief, Masters of the Night-Wind | 「謎煙の主」族長 | 「烟谜主」首领 | NPC
| Cip | シプ | 奇普 | Obsidian Totem Pole manager of "Masters of the Night-Wind" | 「謎煙の主」の黒曜石トーテムポール管理人 | 「烟谜主」曜石图腾柱管理员
| Caholom | カホロム | 卡胡鲁 | | 部族見聞「流れゆく色の記憶」に登場する人物 | | NPC
| Toltec | トルテック | 托尔特克 | | 部族見聞「流れゆく色の記憶」に登場する人物 | | NPC
| Paran | パラン | 帕朗 | | 世界任務「事件は次々に」に登場する人物 | | NPC
| Temach | テマジョ| 特马乔 | | 世界任務「事件は次々に」に登場する人物 | | NPC
| Lliwa | リヴァ | 莉瓦 | | 世界任務「事件は次々に」に登場する人物 | | NPC
| Lamizana | ラミザナ | 拉密萨纳 | | 世界任務「事件は次々に」に登場する人物 | | NPC
| Taruka | タルカ | 塔卢加 | | 世界任務「事件は次々に」に登場する人物 | | NPC
| Oberon | オベロン | 奥伯龙 | | 世界任務「事件は次々に」に登場するクク竜 | | NPC
| "Dopey Dazzler" | 「カラフルノルマ」 | 「炫彩呆子」 | | 「ラクガキユニオン」メンバー。v5.0 期間限定イベント「カラフルギフト」などに登場する人物 | 
| "Mural Maniac" | 「マッドマンハンター」 | 「狂图捕手」 | | 「ラクガキユニオン」リーダー  
| Bona | ポーナ | 玻娜 | | 世界任務「流灰の国の迷える旅人」に登場する人物
| Cocouik | ココウィク | 绿松石 | | 世界任務「流灰の国の迷える旅人」に登場する竜
| Copan | コパン | 科潘 | | 世界任務「流灰の国の迷える旅人」に登場する人物
| Och-Kan | オチカン | 奥奇坎 | | 世界任務「流灰の国の迷える旅人」に登場する竜
| Liriwu | リリウ(過去の人) | 莉莉乌 | | 世界任務「流灰の国の迷える旅人」に名前だけ登場する人物。「帰火聖夜の巡礼」大会参加者とは別人 | | | 
| Waxaklahun Ubah Kan | ワシャクラフン・ウバ・カン | 瓦萨克拉胡巴肯 | | 世界任務「流灰の国の迷える旅人」に登場する竜
| Ixlel | イレール | 伊雷尔 | True Name is "Ix Uxul Tz'ib Bolon Ch'ule-L" | 正式名は「イ・クェクシ・ツボロン・ク・レール(英語表記: True Name is "Ix Uxul Tz'ib Bolon Ch'ule-L"。中国語表記「伊·奎库叙·茨博隆·库·雷尔」)」。世界任務「流灰の国の迷える旅人」に登場する竜 | 真名是「伊・奎库叙・茨博隆・库・雷尔」
| Quenin | クエニン | 夸恩因 | | | | | 夸は誇。testに追加
| Conulaf | コヌラフ | 科奴拉芙 | | 「謎煙の主」の見習い祭司
| Oroluk | オロラク | 奥罗卢柯 | Natlan Angler | ナタの漁師 | 纳塔的渔民
| Magnifico | マニフェコ | 马尼菲科 | | 世界任務「月光に舞え」などに登場する人物 | | NPC | add tags:[natlan, fontinue]
| Mazkal | マズカル | 玛兹嘉 | | 世界任務「竜医の悩み 」に登場する人物
| "Kururuk" | 「グルル」 | 「咕噜噜」 | | 世界任務「竜医の悩み 」に登場するクク竜
| Icayo | イカヨ | 伊卡尤 | | 世界任務「とある竜マニアの平凡な暮らし」に登場する人物
| "Ripple" | 「ナミ」 | 「小波」| | 世界任務「とある竜マニアの平凡な暮らし」に登場するコホラ竜
| "Jade" | 「ヒスイ」 | 「翡翠」| | 世界任務「とある竜マニアの平凡な暮らし」に登場するユムカ仔竜
| "Marigold" | 「マリーゴールド」| 「金盏花」 | | 世界任務「とある竜マニアの平凡な暮らし」に登場するテペトル竜
| | 
| 入力済み | ナマカ | | | 聖火競技場内の竜の世話係 | | | fixed trim
| Kupo Nui | クポ・ヌイ | 库珀·努伊 | |「流泉の衆」の食堂店主 | | | add tags:[natlan]
| 入力済み | マヒナ・ヌイ | 马西娜·努伊 | |「流泉の衆」の食堂接客係 | | | Sorry. fixed mistake notes(wrong job.)
| 入力済み | ワケア・ヌイ | 瓦凯·努伊 | |「流泉の衆」のガイド | | | Sorry. fixed mistake notes(wrong job.)
|P入力済み | ペレ・ヌイ | 佩蕾·努伊 | |「流泉の衆」の温泉の管理人 | | | Sorry. fixed mistake notes(wrong job.)

Location
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | memo |
|---|---|---|---|---|---|---|
| Quahuacan Cliff | クァワカン断崖(クァワカンだんがい) | 翘枝崖
| Tequemecan Valley | テケメカンの谷 | 坚岩隘谷
| Malinalco Grotto | マリナルコ洞窟 | 荧草窟
| Xalac Vale | シャラクの谷 | 漫曛谷
| Scorchwind Trial Grounds | 風炎の試験場 | 焚风试炼处
| Sacrificial Altar of Enigmatic Land | 謎土の祭祀場 | 谜土祭祀场
| Ochkanatlan | オシカ・ナタ | 奥奇卡纳塔
| Furnace of Fiery Embers | 燼火焼尽の地(じんかじょうじんのち) | 烬火炽燃所
| Ashflow Street | アッシュフロー街 | 流灰之街
| Vision Serpent's Sanctum | 幻蛇の宮殿 | 幻蛇之宫
| Vucub Caquix Tower | カキシュの塔 | 火鹦之塔
| Old Core of Chu'ulel | 昔日の統律の心(せきじつのとうりつのこころ?) | 旧日的统律之心
| Core of Chu'ulel | 統律の心(とうりつのこころ?) | 统律之心
| Cradle of Fleeting Dreams | 幻夢のクレイドル | 空梦的起始
| Nursery of Nightmares | ナーサリー・オブ・ナイトメア | 噩梦的温床
| Isle of Tozoz | トゾス島 | 托佐兹之岛
| Legendary Tonatiuh | 伝説の天蛇の船(でんせつのてんじゃのふね) | 传说中的天蛇船
| Tecoloapan Bay | テコロアパン湾 | 浮羽之湾

Books
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | memo |
|---|---|---|---|---|---|---|
| The Tale of Kuntur | クントゥルの物語 | 昆图尔的故事

Foods
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | memo |
|---|---|---|---|---|---|---|
| Mystique Soup | ミステリードリンク | 奇瑰之汤 |||| ★★★★
| Sing Your Heart Out | 高らかな歌声 | 纵声欢唱 |||| ★★★★
| Surf, Turf, and Perch | 山と海と空 | 山与海与天空 |||| ★★★
| Grainfruit Wrap | グレインラップ | 粒果裹裹 |||| ★★
| Sour Sauce Ceviche | セビチェ | 酸汁腌鱼 | Rewar [...]

2024-12-13 07:34 UTC, xicri commented
Thanks as always!
Let me check later.

2024-12-17 22:52 UTC, xicri reviewed
Can you check if the translation is valid?

2024-12-17 22:52 UTC, xicri commented on dataset/dictionary/characters.json5
> +    en: "himpu",
Should it be Capitalized since Himpu is a name?

```suggestion
    en: "Himpu",
```

2024-12-17 22:53 UTC, xicri commented
No, sorry, wrong comment. Forget it.

2024-12-18 00:02 UTC, xicri requested changes
Sorry for the delay.
I have added some review comments.

Since I rebased this branch several times, make sure to overwrite your local branch before you start to modify the code if you update the code on your local machine.

2024-12-22 15:53 UTC, yasuking0304 commented on dataset/dictionary/characters.json5
> +    zhCN: "穆基",
I'm Sorry.  Inputs were missing during transcription.
Fix it.

Character
| English | Japanese | Chinese Simplifed | Note(en)  | Note(ja) | Note(zh-cn)  | type | memo |
|---|---|---|---|---|---|:-:|---|
| Zunan | ジュナン | 朱南 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物
| Mukki | ムッキ | 穆基 | | 部族見聞「塵に帰す花、堕ちる羽」に登場する人物

2024-12-25 10:17 UTC, xicri commented on dataset/dictionary/characters.json5
> +    ja: "リリウ(過去の人)",
Oh, then let's keep "(過去の人)" for now.

I recently think we can allow the same Japanese and Chinese translation in multiple words if English translations are different.
e.g. en: "Genshin Impact" / ja: "原神" vs en: "allogene" / ja: "原神" (Currently Genshin Imapct's Japanese translation is "原神 (タイトル)")

However, currently the test code disallows that. We need to update the test someday.

2024-12-26 01:50 UTC, yasuking0304 commented on dataset/dictionary/characters.json5
> +    ja: "リリウ(過去の人)",
I came up with an idea. I wrote in the issue, but Liliu is also written as Lilim and the notation is shaking. So how about "リリウ / リリム"?

![原神_20241127215307_1](https://github.com/user-attachments/assets/a328bbc3-df18-4a96-9e69-c90160fddc0d)

2024-12-26 02:12 UTC, yasuking0304 commented on dataset/dictionary/characters.json5
> +    ja: "リリウ(過去の人)",
https://github.com/yasuking0304/genshin-langdata/blob/version5.2-prequel/dataset/dictionary/characters.json5#L6135-#L6141

2024-12-26 02:13 UTC, yasuking0304 commented on dataset/dictionary/characters.json5
> +    notes: "正式名は「イ・クェクシ・ツボロン・ク・レール(英語表記: True Name is \"Ix Uxul Tz'ib Bolon Ch'ule-L\"。中国語表記「伊·奎库叙·茨博隆·库·雷尔」)」。世界任務「流灰の国の迷える旅人」に登場する竜",
https://github.com/yasuking0304/genshin-langdata/blob/version5.2-prequel/dataset/dictionary/characters.json5#L6150%E3%83%BCL6164

2024-12-26 02:14 UTC, yasuking0304 commented on dataset/dictionary/characters.json5
> +    zhCN: "穆基",
https://github.com/yasuking0304/genshin-langdata/blob/version5.2-prequel/dataset/dictionary/characters.json5#L5949%E3%83%BCL5962

2024-12-26 02:45 UTC, xicri commented on dataset/dictionary/characters.json5
> +    zhCN: "穆基",
Looks like Z<**h**>unan is still Zunan.

2024-12-26 02:50 UTC, xicri commented
@yasuking0304 Looks like your local linter removes whitespaces between brackets and convert doublequotes to singlequotes. Can you revert them?
Sorry for not updating ESLint to the latest v9 yet...

2024-12-26 02:53 UTC, xicri commented on dataset/dictionary/characters.json5
> +    zhCN: "穆基",
Thanks for fixing Zhunan. Looks good for this.

2024-12-26 02:54 UTC, xicri commented on dataset/dictionary/characters.json5
> +    notes: "正式名は「イ・クェクシ・ツボロン・ク・レール(英語表記: True Name is \"Ix Uxul Tz'ib Bolon Ch'ule-L\"。中国語表記「伊·奎库叙·茨博隆·库·雷尔」)」。世界任務「流灰の国の迷える旅人」に登場する竜",
Thanks, looks good for this thread!

2024-12-26 02:55 UTC, yasuking0304 commented
Got it. This PR has gotten pretty rough, so I'm sorry I'll create another one.

2024-12-26 02:56 UTC, xicri commented
OK 👍

2024-12-26 10:05 UTC, yasuking0304 commented
Issued a new PR.
https://github.com/xicri/genshin-langdata/pull/344

2024-12-28 00:50 UTC, closed without merging