Add Chinese Translation (2022.12.5)
xicri/genshin-langdata pull request #80
Opened 2022-12-05 14:06 UTC by Bill-Haku

I added the Chinese expressions of the words you added in the `y-events.json5`. Thanks for your review.

2022-12-06 23:39 UTC, xicri requested changes

2022-12-06 23:39 UTC, xicri commented on dataset/dictionary/y-events.json5
> +    notes: "v3.2 期間限定イベント「ワンダフルキノコンピック」で仲間にできるキノコンに対し、選択によってはこの名前をつけることができる。ガイアの元素スキル発動時のセリフ[「こいつはどうだ?」(Dodge this!)(这个如何？)](/dodge-this/) 及び[「おとなしくしやがれ!」(Cool it!)(冻结吧！)](/cool-it/) 及び「老实点儿」に由来すると思わ
I will add translation for 老实点儿 since only Chinese speakers understand this without translations.
I will add this weekend.

2022-12-06 23:39 UTC, xicri commented on dataset/dictionary/y-events.json5
> +    notes: "v3.2 期間限定イベント「ワンダフルキノコンピック」で仲間にできるキノコンに対し、選択によってはこの名前をつけることができる。ディルックの元素爆発発動時のセリフ[「判決を―下す!」(Your verdict is...!)(审判——喝啊！)](/your-verdict-is/) 及び[「裁きを、受けよ!」(Time for ― retribution!)(在此——宣判
Splitting with slash looks a bit more natural to me.

```suggestion
    notes: "v3.2 期間限定イベント「ワンダフルキノコンピック」で仲間にできるキノコンに対し、選択によってはこの名前をつけることができる。ディルックの元素爆発発動時のセリフ[「判決を―下す!」(Your verdict is...! / 审判——喝啊！)](/your-verdict-is/) 及び[「裁きを、受けよ!」(Time for ― retribution! / 在此——宣判！)](/time-for-retribution/)に由来すると思われる。",
```

2022-12-07 02:06 UTC, Bill-Haku commented on dataset/dictionary/y-events.json5
> +    notes: "v3.2 期間限定イベント「ワンダフルキノコンピック」で仲間にできるキノコンに対し、選択によってはこの名前をつけることができる。ガイアの元素スキル発動時のセリフ[「こいつはどうだ?」(Dodge this!)(这个如何？)](/dodge-this/) 及び[「おとなしくしやがれ!」(Cool it!)(冻结吧！)](/cool-it/) 及び「老实点儿」に由来すると思わ
Thanks. So when are you going to merge this PR?

2022-12-07 03:25 UTC, xicri commented on dataset/dictionary/y-events.json5
> +    notes: "v3.2 期間限定イベント「ワンダフルキノコンピック」で仲間にできるキノコンに対し、選択によってはこの名前をつけることができる。ガイアの元素スキル発動時のセリフ[「こいつはどうだ?」(Dodge this!)(这个如何？)](/dodge-this/) 及び[「おとなしくしやがれ!」(Cool it!)(冻结吧！)](/cool-it/) 及び「老实点儿」に由来すると思わ
Ah, I will merge it now. I will add translation for 老实点儿 after I merge this PR.

2022-12-07 03:25 UTC, xicri approved these changes

2022-12-07 03:25 UTC, merged